#!/usr/bin/env bash
#ddddddasaadsassadddaff
(echo "Active Internet connections (only servers)"; echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"; ss -tulnpH | awk '{printf "%-5s %6s %6s %-23s %-23s %-11s %s\n", $1, $2, $3, $4, $5, $6, $7}'; echo "Active UNIX domain sockets (only servers)"; echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"; ss -xplH | grep LISTEN | awk '{printf "%-5s %6s %-11s %-10s %-13s %-8s %-18s %s\n", "unix", $2, $3, $4, $5, $6, $7, substr($0, index($0,$8)) }')



